<aside>

    <div class="MenuitemTitle" >
      <span lang="en" id="itemMP01">Menu</span></div>
    <div class="MenuitemHeader" ><span lang="en" id="itemMP02">Links</span></div>

    <ul id="MenuRCRitemlink1" class="MenuitemList">
        <li class="Menuitem"><a href="#"><span lang="en" id="itemMP011">Link #1</span></a> </li>
        <li class="Menuitem"><a href="#"><span lang="en" id="itemMP012">Link #2</span></a> </li>
        <li class="Menuitem"><a href="#"><span lang="en" id="itemMP13">Link #3</span></a> </li>
        <li class="Menuitem"><a href="#"><span lang="en" id="itemMP14">Link #4</span></a> </li>
        <li class="Menuitem"><a href="#"><span lang="en" id="itemMP15">Link #5</span></a> </li>
        <li class="Menuitem"><a href="#"><span lang="en" id="itemMP16">Link #6</span></a> </li>
         <li class="Menuitem"><a href="#"><span lang="en" id="itemMP17">Link #7</span></a> </li>
    </ul>
    <div class="MenuitemHeader" ><span lang="en" id="itemMP20">Search</span></div>
    <ul id="MenuRCRitemlink99" class="MenuitemList">
        <li class="Menuitem"><a href="#"><span lang="en" id="itemMP111">Link #1</span></a> </li>
        <li class="Menuitem"><a href="#"><span lang="en" id="itemMP121">Link #2</span></a> </li>
    </ul>




    <div class="MenuitemHeader" ><span id="itemMP30" lang="en">Reports</span></div>
    <ul id="MenuRCRitemlink3" class="MenuitemList">
        <li class="Menuitem"><a href="#"><span lang="en" id="itemMP1190">Link #1</span></a> </li>
        <li class="Menuitem"><a href="#"><span lang="en" id="itemMP1291">Link #2</span></a> </li>
    </ul>


    <div class="MenuitemHeader" ><span lang="en" id="itemMP40">Other</span></div>
    <ul id="MenuRCRitemlink2" class="MenuitemList">
        <li class="Menuitem"><a href="#"><span lang="en" id="itemMP45">Link #1</span></a> </li>
        <li class="Menuitem"><a href="#"><span lang="en" id="itemMP56">Link #2</span></a> </li>
    </ul>


</aside>
