<main>

    <div id="mainwindow">
<h1><span id="HeaderLogo" lang="en">Nerd's Creed - By the Mandi Monster</span></h1>
        <p>
   <span lang="en" id="HeaderSubLogo">&nbsp;</span>
        </p>

<div id="theVideoDiv">
<table class="gwTable">
<tr>
<td>
<iframe width="560" height="315" 
src="https://www.youtube.com/embed/LoohIjWBWhg" frameborder="0" 
allow="autoplay; encrypted-media" allowfullscreen></iframe>
</td>
<td class="gwTop">
<table class="gwFrameBorder">
<tr>
<td>Original:</td><td><a href="https://hellopoetry.com/poem/975624/nerds-creed/">Nerd's Creed Poem</a></td>
</tr>

<tr>
<td>Image:</td><td><a href="http://geekwisdom.org/vids/nerdscreed.png">nerdscreed.png</a></td>
</tr>
<tr>
<td>License:</td><td><a href="https://hellopoetry.com/TheMandiMonster/">(c) The Mandi Monster - Used with Permission</a></td>
</tr>
<tr>
<td>Source Attribution:</td><td><a href="https://hellopoetry.com/TheMandiMonster/">Hello Poetry</a></td>
</tr>
</table>
</td>
</tr>
</table>

<div id="fbshare" class="fb-share-button" 
    data-href="" 
    data-layout="button_count">
  </div>
<span>
&nbsp;	
<a class="twitter-share-button"
  href="https://twitter.com/intent/tweet?text=#GeekWisdom">
Tweet</a>
</span>
</div>
</div>

</main>
