<!-- FOR REALLY OLD BROWSERS AND NO JAVASCRIPT -->

<div id="noJavascriptDIV" class="oldStyle">
<div class="oldindent">
<h1 > Be Proud of your Inner Geek!</h1>
<h2 >Mission</h2>
<p >
The mission of GeekWisdom is to share knowledge and information (education),  
to seek out new technology and new gadget's and gizmos' (hackers)
to boldy go where no geek has gone before.
</p>
<ul id="oldmenu">
<li><img alt="NEW" src="legacy/new.gif" /><a href="https://blog.geekwisdom.org">Read The Blog</a></li>
<li><a href="https://www.geekwisdom.org/vids">Watch a Random Video</a></li>
<li><a href="https://www.geekwisdom.org/quotes">Read a Random Quote</a></li>
<li><a href="https://www.geekwisdom.org/games">Play a Game</a></li>

</ul>

<p>
<a href="https://www.mozilla.org/en-US/firefox/new/"><img alt="Get Mozilla"  src="./legacy/NetscapeNow.gif" /></a>
<a href="https://www.microsoft.com/en-ca/download/internet-explorer.aspx"><img alt="Get IE" src="./legacy/ie_animated.gif" /></a>
<a href="https://www.google.com/chrome/"><img alt="Get Chrome" src="./legacy/chrome_badge_sm.png" /></a>
</p>
<p>
<img alt="Why is this text so old?" src="./legacy/so_old.png" style="width:68%;height:68%;" />
<img alt="Dancing Bannana" src="./legacy/bannana.gif" style="text-align:right;" />

</p>
</div>
</div>
